bot:
  prefix: "!"
  owner: "142918778232111104"
  helpCommand: "huh"

audio:
  lofiURL: "https://youtu.be/5qap5aO4i9A"
  rockURL: "https://www.youtube.com/playlist?list=PLFiObAyJn6E4xsjQGKzErYMznxmp6Ssn3"
  noScaredURL: "https://youtu.be/fL-bM8UKIWs"
  hipToBeSquareURL: "https://youtu.be/LB5YkmjalDg"

image:
  batemanAxeURL: "https://i.kym-cdn.com/entries/icons/mobile/000/008/301/Patrick_Bateman_With_an_Axe_Banner.jpg"
